name: Lint with flake8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. Remove --exit-zero to enforce failures.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
